services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - matomodbvol:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=matomo
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./.env

  app:
    image: matomo:fpm-alpine
    restart: unless-stopped
    links:
      - db
    volumes:
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./.env

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - matomo:/var/www/html:z,ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    ports:
      - 8085:80

volumes:
  matomodbvol:
  matomo:
